version: 2

sources:
  - name: raw
    schema: gz_raw_data

    # 5.1 Opsiyonel - Tazelik Testi (Eğitimde vardı, ekliyoruz)
    loaded_at_field: "CAST(date_date AS TIMESTAMP)"
    freshness:
      warn_after: { count: 90, period: day }

    tables:
      # --- SALES TABLOSU ---
      - name: sales
        identifier: raw_gz_sales
        description: Greenweez'in satışları / her orders_id'de bulunan bir product_id için bir satırımız var
        columns:
          - name: date_date
            description: Satın alma tarihi
          - name: orders_id
            description: Kargo (ship) tablosuna yabancı anahtar
          - name: pdt_id # Kaynakta 'pdt_id' olduğunu unutma
            description: Ürün (product) tablosuna yabancı anahtar
          - name: revenue
            description: Müşterinin ürün için ödediği tutar
          - name: quantity
            description: Belirli bir sipariş için satın alınan ürün miktarı
        tests:
          # Sales için birleşik benzersizlik testi
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - orders_id
                - pdt_id

      # --- PRODUCT TABLOSU ---
      - name: product
        identifier: raw_gz_product
        description: Greenweez'in ürünleri
        columns:
          - name: products_id
            description: Birincil anahtar (Primary key)
            tests:
              - unique # Test 1: Benzersiz olmalı
              - not_null # Test 2: Boş olmamalı
          - name: purchse_price # Kaynakta 'purchse_price' olduğunu unutma
            description: Ürünün satın alma fiyatı

      # --- SHIP TABLOSU ---
      - name: ship
        identifier: raw_gz_ship
        description: Greenweez siparişleri için nakliye verileri
        columns:
          - name: orders_id
            description: Birincil anahtar (Primary key)
            tests:
              - unique # Test 1: Benzersiz olmalı
              - not_null # Test 2: Boş olmamalı
          - name: shipping_fee
            description: Müşterinin kargo için ödediği ücret
          - name: logcost # Kaynakta 'logcost' olduğunu unutma
            description: Dağıtım merkezindeki hazırlık maliyeti
          - name: ship_cost
            description: Greenweez'in taşıyıcıya ödediği kargo maliyeti
