version: 2

sources:
  - name: raw
    schema: gz_raw_data

   
    loaded_at_field: "CAST(date_date AS TIMESTAMP)"
    freshness:
      warn_after: { count: 90, period: day }

    tables:
      # --- SALES TABLOSU ---
      - name: sales
        identifier: raw_gz_sales
        description: Greenweez'in satışları / her orders_id'de bulunan bir product_id için bir satırımız var
        columns:
          - name: date_date
            description: Satın alma tarihi
          - name: orders_id
            description: Kargo (ship) tablosuna yabancı anahtar
          - name: pdt_id 
            description: Ürün (product) tablosuna yabancı anahtar
          - name: revenue
            description: Müşterinin ürün için ödediği tutar
          - name: quantity
            description: Belirli bir sipariş için satın alınan ürün miktarı
        tests:
          # Sales için birleşik benzersizlik testi
          - dbt_utils.unique_combination_of_columns:

              arguments:
                combination_of_columns:
                  - orders_id
                  - pdt_id

      # --- PRODUCT TABLOSU ---
      - name: product
        identifier: raw_gz_product
        description: Greenweez'in ürünleri
        columns:
          - name: products_id
            description: Birincil anahtar (Primary key)
            tests:
              - unique 
              - not_null 
          - name: purchse_price
            description: Ürünün satın alma fiyatı

      # --- SHIP TABLOSU ---
      - name: ship
        identifier: raw_gz_ship
        description: Greenweez siparişleri için nakliye verileri
        columns:
          - name: orders_id
            description: Birincil anahtar (Primary key)
            tests:
              - unique 
              - not_null
          - name: shipping_fee
            description: Müşterinin kargo için ödediği ücret
          - name: logcost 
            description: Dağıtım merkezindeki hazırlık maliyeti
          - name: ship_cost
            description: Greenweez'in taşıyıcıya ödediği kargo maliyeti

      # --- YENİ EKLENEN PAZARLAMA KAYNAKLARI ---
      - name: adwords
        identifier: raw_gz_adwords

      - name: bing
        identifier: raw_gz_bing

      - name: criteo
        identifier: raw_gz_criteo

      - name: facebook
        identifier: raw_gz_facebook